server:
  port: 18555

spring:
  application:
    name: canal

# Eureka注册中心配置信息
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true

# hystrix配置
hystrix:
  command:
    default:
      exection:
        timeout:
          enabled: true
        isolation:
          strategy: SEMAPHORE

#canal配置
canal:
  client:
    instances:
      example:
        host: 192.168.137.118
        port: 11111
