server:
  port: 7920
spring:
  application:
    name: user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.137.118:3307/changgou_user?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
  redis:
    port: 6379
    host: 192.168.137.118
eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9:
  eyJzY29wZSI6WyJhcHAiXSwibmFtZSI6bnVsbCwiaWQiOm51bGwsImV4cCI6MTU5ODAyOTg0MCwiYXV0aG9yaXRpZXMiOlsic2Vja2lsbF9saXN0IiwiZ29vZHNfbGlzdCJdLCJqdGkiOiJiYmU3YzgwYi1iZjNjLTRjMzEtYTcxOC1lZDg2NjdkNzcwODUiLCJjbGllbnRfaWQiOiJjaGFuZ2dvdSIsInVzZXJuYW1lIjoic3ppdGhlaW1hIn0:
    IrssMhw6e1cKkJ0HlkrtecO0Crxexnq2PMrk2UCNDbI53VSpkNKOo-jgrwxAw97qc0XBpLJfVWQjK5yqfftZgSrGezwnUUA7zF_FUOTkjEKDLbFYMva39Y66YPDCE-yNYO0m927-Z0r5mEowmWO4EemALcWAzACUdesddCYOFWBRQ_bfDrH-IJ5ZyMEVSJxvZUgZUR3Xa77NVfLTWrjaKxQDeCZM94VmOg1N4FfhYpRXOgm4kfjHXRh2KJmYrvTUb40a5Y8v2NcH9LOf1yPVAQFR25RDmiAyxplqpFYmJfmgCDyhVUjRRSsLXdZbApQI2yqavl1kaXtdiHLXGD8WOg:
# Eureka注册中心配置信息
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true